<a href="https://colab.research.google.com/github/divyanshun9/UPI-fraud-detection/blob/main/sourcecode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)

Mounted at /content/gdrive

In [11]:
credit_card_data = pd.read_csv('/content/gdrive/MyDrive/creditcard.csv')

In [12]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [13]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [14]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [15]:
credit_card_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

Data here his highly inconsistent


---

0=normal transaction


1=fraud transaction

In [16]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [17]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [18]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [20]:
#taking only 492 samples out of 284315 samples of class 1 so that we can train out model accordingly
legit_sample = legit.sample(n=492)

In [21]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [22]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
111466,72239.0,-1.491631,1.021777,2.168778,1.369147,0.651211,0.594893,0.319938,0.069369,-0.377851,...,0.085738,0.274001,-0.450616,-0.621054,0.674601,0.086970,-0.497533,0.149633,0.00,0
162815,115393.0,-1.210077,-1.237450,2.540085,-1.215712,-0.981082,3.157793,0.125357,0.779537,1.718938,...,0.259858,0.932276,0.183845,-1.565267,0.213337,1.254106,-0.162221,-0.169577,290.96,0
141042,84094.0,1.295749,0.310453,0.325538,0.494271,-0.146797,-0.683574,0.120897,-0.231833,-0.075591,...,-0.278328,-0.752549,0.062467,-0.091937,0.318446,0.122045,-0.023064,0.016195,1.98,0
26048,33887.0,-1.800353,1.178190,-0.253781,-0.084551,-0.203453,1.210077,-0.899727,1.784134,-0.800921,...,0.465525,0.953760,0.284905,-1.005128,-0.585832,0.405841,-0.676501,-0.212753,11.72,0
230448,146335.0,1.946387,-0.886444,-0.930014,-1.708371,-0.441699,-0.105527,-0.604971,0.081957,1.876416,...,-0.123429,-0.294926,0.275577,0.223056,-0.378896,-0.546086,0.017517,-0.035968,57.85,0

In [23]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [24]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95287.936992,-0.066267,-0.034058,-0.060282,0.016716,0.125461,-0.094246,-0.034135,-0.029947,0.040039,...,0.011167,0.028007,-0.023214,0.028699,-0.046822,-0.028721,-0.011693,0.006152,0.025146,90.063130
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [25]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [26]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
111466   72239.0 -1.491631  1.021777  2.168778  1.369147  0.651211  0.594893
162815  115393.0 -1.210077 -1.237450  2.540085 -1.215712 -0.981082  3.157793
141042   84094.0  1.295749  0.310453  0.325538  0.494271 -0.146797 -0.683574
26048    33887.0 -1.800353  1.178190 -0.253781 -0.084551 -0.203453  1.210077
230448  146335.0  1.946387 -0.886444 -0.930014 -1.708371 -0.441699 -0.105527
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
111466  0.319938  0.069369 -0.377851  ... -0.248400  0.085738  0.274001
162815  0.125357  0.779537  1.718938  ...  0.572652  0.259858  0.932276
141042  0.120897 -0.231833 -0.075591  ... -0.011263 -0.278328 -0.752549
26048  -0.899727  1.784134 -0.800921  ... -0.670235  0.465525  0.953760
230448 -0.604971  0.081957  1.876416  ... -0.015553 -0.123429 -0.294926
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
111466 -0.450616 -0.621054  0.674601  0.086970 -0.497533  0.149633    0.00
162815  0.183845 -1.565267  0.213337  1.254106 -0.162221 -0.169577  290.96
141042  0.062467 -0.091937  0.318446  0.122045 -0.023064  0.016195    1.98
26048   0.284905 -1.005128 -0.585832  0.405841 -0.676501 -0.212753   11.72
230448  0.275577  0.223056 -0.378896 -0.546086  0.017517 -0.035968   57.85
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [28]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [29]:
model = LogisticRegression()

In [30]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

LogisticRegression()

In [37]:
# training the RandomForestClassifier Model with Training Data
clf = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
clf.fit(X_train, Y_train)

RandomForestClassifier(max_depth=5, random_state=42)

In [42]:
# training the DecisionTreeClassifier Model with Training Data
c = DecisionTreeClassifier(max_depth=5, random_state=42)
c.fit(X_train, Y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [47]:
# accuracy on training data
X_train_prediction_lr = model.predict(X_train)
training_data_accuracy_lr = accuracy_score(X_train_prediction_lr, Y_train)
X_train_prediction_rf = clf.predict(X_train)
training_data_accuracy_rf = accuracy_score(X_train_prediction_rf, Y_train)
X_train_prediction_dt = c.predict(X_train)
training_data_accuracy_dt = accuracy_score(X_train_prediction_dt, Y_train)

In [48]:
print('Accuracy on Training data using logistic regression: ', training_data_accuracy_lr)
print('Accuracy on Training data using random forest classifier: ', training_data_accuracy_rf)
print('Accuracy on Training data using decision tree classifier: ', training_data_accuracy_dt)

Accuracy on Training data using logistic regression:  0.9339263024142312
Accuracy on Training data using random forest classifier:  0.96569250317662
Accuracy on Training data using decision tree classifier:  0.9783989834815756

In [49]:
# accuracy on test data
X_test_prediction_lr = model.predict(X_test)
test_data_accuracy_lr = accuracy_score(X_test_prediction_lr, Y_test)

X_test_prediction_rf = clf.predict(X_test)
test_data_accuracy_rf = accuracy_score(X_test_prediction_rf, Y_test)

X_test_prediction_dt = c.predict(X_test)
test_data_accuracy_dt = accuracy_score(X_test_prediction_dt, Y_test)

In [50]:
print('Accuracy score on Test Data using logistic regression : ', test_data_accuracy_lr)
print('Accuracy score on Test Data random forest classifier : ', test_data_accuracy_rf)
print('Accuracy score on Test Data decision tree classifier: ', test_data_accuracy_dt)

Accuracy score on Test Data using logistic regression :  0.9238578680203046
Accuracy score on Test Data random forest classifier :  0.9086294416243654
Accuracy score on Test Data decision tree classifier:  0.8883248730964467